"""autogenerate migration scripts for sqlalchemy models

Revision ID: fc4c9fb8e44f
Revises: 392d72db2a3a
Create Date: 2024-07-30 07:41:25.466824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc4c9fb8e44f'
down_revision: Union[str, None] = '392d72db2a3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
